/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Job = IDL.Record({
  'id' : IDL.Nat,
  'salary' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'company' : IDL.Text,
  'address' : IDL.Text,
  'department' : IDL.Text,
  'position' : IDL.Text,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CandidateApplication = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Text,
  'subject' : IDL.Text,
  'resumeBase64' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Text,
  'email' : IDL.Text,
  'district' : IDL.Text,
  'experience' : IDL.Text,
  'state' : IDL.Text,
  'preferredLocation' : IDL.Text,
  'applyingFor' : IDL.Text,
  'gender' : IDL.Text,
  'phone' : IDL.Text,
  'qualification' : IDL.Text,
  'college' : IDL.Text,
  'resumeFileName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJob' : IDL.Func([Job], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteApplication' : IDL.Func([IDL.Nat], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'getAllApplications' : IDL.Func(
      [],
      [IDL.Vec(CandidateApplication)],
      ['query'],
    ),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepartments' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getJobsByDepartment' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitApplication' : IDL.Func([CandidateApplication], [IDL.Nat], []),
  'updateJob' : IDL.Func([IDL.Nat, Job], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'salary' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'company' : IDL.Text,
    'address' : IDL.Text,
    'department' : IDL.Text,
    'position' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CandidateApplication = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Text,
    'subject' : IDL.Text,
    'resumeBase64' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Text,
    'email' : IDL.Text,
    'district' : IDL.Text,
    'experience' : IDL.Text,
    'state' : IDL.Text,
    'preferredLocation' : IDL.Text,
    'applyingFor' : IDL.Text,
    'gender' : IDL.Text,
    'phone' : IDL.Text,
    'qualification' : IDL.Text,
    'college' : IDL.Text,
    'resumeFileName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJob' : IDL.Func([Job], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteApplication' : IDL.Func([IDL.Nat], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'getAllApplications' : IDL.Func(
        [],
        [IDL.Vec(CandidateApplication)],
        ['query'],
      ),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepartments' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getJobsByDepartment' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitApplication' : IDL.Func([CandidateApplication], [IDL.Nat], []),
    'updateJob' : IDL.Func([IDL.Nat, Job], [], []),
  });
};

export const init = ({ IDL }) => { return []; };